CREATE TABLE USERS
(	ID BIGINT CONSTRAINT USERS_ID_NN NOT NULL,
    CHAT_ID BIGINT CONSTRAINT USERS_CHAT_ID_NN NOT NULL,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    USER_NAME VARCHAR,
    REGISTERED_AT TIMESTAMP,
    CONSTRAINT USERS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_CHAT_ID_UN UNIQUE (CHAT_ID)
);

CREATE SEQUENCE user_seq START WITH 1;
